### Create a skill
POST {{url}}/skills
Content-Type: application/json

{
  "name": "Kotlin",
  "category": "PROG_LANG",
  "description": "JVM language"
}

### Get all skills
GET {{url}}/skills
Accept: application/json

### Get skill by id
GET {{url}}/skills/4
Accept: application/json

### Update skill
PUT {{url}}/skills/1
Content-Type: application/json

{
  "name": "Kotlin",
  "category": "PROG_LANG",
  "description": "Updated description"
}

### Delete skill
DELETE {{url}}/skills/1
Accept: application/json
